// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1WMN_uXH_9S5Tp-CaRlLgg1Y3kI7cJtY',
    appId: '1:1058932627501:web:4de10ece76894f7f43c0a4',
    messagingSenderId: '1058932627501',
    projectId: 'strong-imagery-461714-n2',
    authDomain: 'strong-imagery-461714-n2.firebaseapp.com',
    storageBucket: 'strong-imagery-461714-n2.firebasestorage.app',
    measurementId: 'G-G2Z29J9HYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASRnYzHqwTw_OVr8kA7BkdD2ZBj-uZOAc',
    appId: '1:1058932627501:android:de17addb714b940943c0a4',
    messagingSenderId: '1058932627501',
    projectId: 'strong-imagery-461714-n2',
    storageBucket: 'strong-imagery-461714-n2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB28dWcdfh0wTl7zIQDBBWHr6oLL8a7AMw',
    appId: '1:1058932627501:ios:9af3947b7d92ae5843c0a4',
    messagingSenderId: '1058932627501',
    projectId: 'strong-imagery-461714-n2',
    storageBucket: 'strong-imagery-461714-n2.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB28dWcdfh0wTl7zIQDBBWHr6oLL8a7AMw',
    appId: '1:1058932627501:ios:9af3947b7d92ae5843c0a4',
    messagingSenderId: '1058932627501',
    projectId: 'strong-imagery-461714-n2',
    storageBucket: 'strong-imagery-461714-n2.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1WMN_uXH_9S5Tp-CaRlLgg1Y3kI7cJtY',
    appId: '1:1058932627501:web:7649b09cf612013043c0a4',
    messagingSenderId: '1058932627501',
    projectId: 'strong-imagery-461714-n2',
    authDomain: 'strong-imagery-461714-n2.firebaseapp.com',
    storageBucket: 'strong-imagery-461714-n2.firebasestorage.app',
    measurementId: 'G-GHX2D5TS8D',
  );
}
